# Site settings
title: lopqto's adventures
url: "https://lopqto.me"
baseurl: ""
timezone: Asia/Tehran
description: >
  Personal blog of Hamidreza Babaee. Reverse engineering, malware analysis, and vulnerability researching.
lang: en

# Personal information
author: Hamidreza Babaee
avatar: "https://gravatar.com/avatar/2299d4e1a3508f63aaac7d956f41784372595562de6274dc0157c107ae2c4d07?v=1755405717000&size=256"
profile: Poking around to find out.
profile_links:
  GitHub: "https://github.com/lopqto"
  X/Twitter: "https://x.com/lopqto"

excerpt_separator: <!--more-->

header:
  links: # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Category: /category/

permalink: /archivers/:title
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  - jekyll-sitemap

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
